lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: null

# Site settings
title: Shersheial Borisute
description: Software Engineer sharing insights into modern development practices, covering product development, software engineering best practices, and mobile development experiences. My most successful project has been the Siddur Torah Ohr app - a Jewish prayer book used by tens of thousands of people monthly.
url: "https://sharshi.com"
baseurl: ""

# Pagination
paginate: 5
paginate_path: "/posts/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-paginate

permalink: /posts/:year/:month/:day/:title/