lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Site settings
title: Shersheial Borisute
description: Software Engineer
url: "https://sharshi.com"
baseurl: ""

# Pagination
paginate: 5
paginate_path: "/post/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /post/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-paginate
